### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-shostak#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
6) Відомо, що з серпня 2021 року GitHub-сервер забороняє клонувати Private GitHub-репозиторії 
через процедуру аутентифікації на основі паролю. Опишіть, будь ласка, 
інші два засоби безпеки, які дозволяють зробити таке клонування.

**Comment by DLuckYD** [comment]
GitHub запровадив використання PAT для аутентифікації під час оновлення репозиторіїв, щоб підвищити рівень безпеки. До серпня 2021 року аутентифікація часто здійснювалася за допомогою паролів, але це менш безпечний метод, особливо в умовах зростання кібератак. Використання PAT дозволяє мати більш контрольовані й захищені доступи до репозиторію, оскільки вони можуть бути створені з обмеженими правами доступу та легко відкликані у випадку компрометації. Це також зменшує ризик витоку паролів, оскільки токени можуть бути створені для конкретних задач і не розкривають основний пароль користувача.

**Comment by DLuckYD** [comment]
Це попереднії Issue

![image](https://github.com/user-attachments/assets/4c3e2cdd-7396-4443-9d49-60067c0b3b57)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
